name = "rp"
compatibility_date = "2026-07-14"

[vars]
N = "Re Player"
P = "masteradmin"
US = ""
# UI = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
# UH = "https://cloud.umami.is"
# UD = "example.com,www.example.com"

[[d1_databases]]
binding = "DB"
database_name = "re-play"
database_id = "269494cb-1be0-4292-adbb-15c32c29255f"
