name = "rp"
compatibility_date = "2026-07-14"

[vars]
N = "Re Player"
P = "masteradmin"
US = ""
# UI = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
# UH = "https://cloud.umami.is"
# UD = "example.com,www.example.com"

[[d1_databases]]
binding = "DB"
database_name = "rp"
database_id = "00000000-0000-0000-0000-000000000000"
